version: '3.7'

services:
    app:
        image: node:latest
        entrypoint: 'tail -f /dev/null'
        working_dir: /app
        volumes:
            - ./:/app:rw,cached
        networks:
            - dev_net

    mongo:
        image: mongo:4.2
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - dev_net

networks:
    dev_net:
        external: true
